# Changes here will be overwritten by Copier
_commit: v0.10.0
_src_path: gh:bhklab/bhklab-project-template
author_email: bhklab.jermiahjoseph@gmail.com
author_full_name: Jermiah Joseph
github_username: jjjermiah
has_additional_authors: false
project_description: Create TRE for gCSI
project_name: gCSI TreatmentResponse Snakemake
project_slug: gcsi-treatmentresponse-snakemake
publish_to_github: true
python_version: '3.12'
repo_location: BHKLAB-DataProcessing
